ALTER TABLE generation_runs ADD COLUMN provider_adapter_version VARCHAR(100);
ALTER TABLE generation_runs ADD COLUMN result_contract_version VARCHAR(100);
ALTER TABLE generation_runs ADD COLUMN schema_version VARCHAR(100);
ALTER TABLE generation_runs ADD COLUMN validator_version VARCHAR(100);
ALTER TABLE generation_runs ADD COLUMN source_requirement_version BIGINT;
ALTER TABLE generation_runs ADD COLUMN source_snapshot_provenance VARCHAR(30);

ALTER TABLE generation_runs
  ADD CONSTRAINT ck_generation_runs_snapshot_provenance
  CHECK (source_snapshot_provenance IS NULL OR source_snapshot_provenance IN ('EXACT', 'LEGACY_RECONSTRUCTED'));

CREATE TABLE generation_criterion_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    generation_run_id UUID NOT NULL REFERENCES generation_runs(id) ON DELETE CASCADE,
    source_acceptance_criterion_id UUID NOT NULL,
    criterion_key VARCHAR(20) NOT NULL,
    description VARCHAR(4000) NOT NULL,
    sort_order INTEGER NOT NULL CHECK (sort_order >= 0),
    source_requirement_version BIGINT NOT NULL,
    provenance VARCHAR(30) NOT NULL CHECK (provenance IN ('EXACT', 'LEGACY_RECONSTRUCTED')),
    UNIQUE (generation_run_id, criterion_key),
    UNIQUE (generation_run_id, sort_order)
);

CREATE INDEX idx_generation_criterion_snapshots_run
  ON generation_criterion_snapshots(generation_run_id, sort_order);

CREATE TABLE snapshot_traceability_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criterion_snapshot_id BIGINT NOT NULL REFERENCES generation_criterion_snapshots(id) ON DELETE CASCADE,
    test_case_id UUID NOT NULL REFERENCES test_cases(id) ON DELETE CASCADE,
    coverage_type VARCHAR(20) NOT NULL CHECK (coverage_type IN ('DIRECT', 'PARTIAL', 'SUPPORTING')),
    confidence DECIMAL(5,4) NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (criterion_snapshot_id, test_case_id)
);

CREATE INDEX idx_snapshot_traceability_links_case
  ON snapshot_traceability_links(test_case_id);

ALTER TABLE test_case_revisions ADD COLUMN change_type VARCHAR(30);
ALTER TABLE test_case_revisions ADD COLUMN change_reason VARCHAR(4000);
ALTER TABLE test_case_revisions ADD COLUMN source_audit_event_id UUID;
ALTER TABLE test_case_revisions
  ADD CONSTRAINT uq_test_case_revisions_source_audit_event UNIQUE (source_audit_event_id);

-- Rows created before V6 cannot prove the exact provider adapter or validator binary.
UPDATE generation_runs
SET provider_adapter_version = 'legacy-unknown',
    result_contract_version = 'legacy-unknown',
    schema_version = 'manual-test-schema-v1',
    validator_version = 'legacy-unknown',
    source_requirement_version = (
      SELECT requirement.version
      FROM requirements requirement
      WHERE requirement.id = generation_runs.requirement_id
    ),
    source_snapshot_provenance = 'LEGACY_RECONSTRUCTED';

-- This reconstructs currently knowable criteria; it never claims to restore deleted history.
INSERT INTO generation_criterion_snapshots (
    generation_run_id,
    source_acceptance_criterion_id,
    criterion_key,
    description,
    sort_order,
    source_requirement_version,
    provenance
)
SELECT
    run.id,
    criterion.id,
    criterion.criterion_key,
    criterion.description,
    criterion.sort_order,
    requirement.version,
    'LEGACY_RECONSTRUCTED'
FROM generation_runs run
JOIN requirements requirement ON requirement.id = run.requirement_id
JOIN acceptance_criteria criterion ON criterion.requirement_id = requirement.id;

INSERT INTO snapshot_traceability_links (
    criterion_snapshot_id,
    test_case_id,
    coverage_type,
    confidence,
    created_at
)
SELECT
    snapshot.id,
    legacy.test_case_id,
    legacy.coverage_type,
    legacy.confidence,
    legacy.created_at
FROM traceability_links legacy
JOIN test_cases test_case ON test_case.id = legacy.test_case_id
JOIN generation_criterion_snapshots snapshot
  ON snapshot.generation_run_id = test_case.generation_run_id
 AND snapshot.source_acceptance_criterion_id = legacy.acceptance_criterion_id;
