package com.testforge.requirement.domain;

public enum AmbiguityCategory {
  MISSING_PRECONDITION,
  UNCLEAR_BUSINESS_RULE,
  MISSING_ERROR_BEHAVIOR,
  MISSING_PERMISSION_RULE,
  MISSING_DATA_CONSTRAINT,
  CONTRADICTORY_REQUIREMENT,
  UNDEFINED_TERM,
  OTHER
}
